version: '3.9'

services:

  #php+apache
  php:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: etl-conta_backend
    working_dir: /var/www/html/
    depends_on:
      - mongo
      - redis
    networks:
      - etl-conta_network
    ports:
      - "3080:80"
    volumes:
      - "./backend:/var/www/html"
      - "./apache/sites-enabled/:/etc/apache2/sites-enabled/"
    environment:
      FRONTEND_HOST: node:3080
      # MYSQL_HOST: mysql
      # MYSQL_PASSWORD: user
      # MYSQL_USER: user
      # MYSQL_DATABASE: etl-conta_database
      REDIS_HOST: redis 
      REDIS_PORT: 6379
      REDIS_PASSWORD: senha

  #node
  node:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: etl-conta_frontend
    working_dir: /home/node/app
    stdin_open: true
    tty: true
    command: bash -c "npm i && npm run dev"
    networks:
      - etl-conta_network
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/home/node/app"
    environment:
      # BACK_HOST: php:8080/api
      CHOKIDAR_USEPOLLING: 'true'
      HOST: '0.0.0.0'

  #mongo
  mongo: 
    image: mongo
    restart: "no"
    container_name:  etl-conta_mongo
    networks:
      - etl-conta_network
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: etl-conta
    volumes:
      - "mongo-db:/data/db"
      - "mongo-configdb:/data/configdb"

  #mongo-express
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: etl-conta-mongo-express
    networks:
      - etl-conta_network
    ports:
      - 8081:8081  
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mexpress
    links:
      - mongo  


  #redis
  redis:
    image: redis:7.0
    container_name: etl-conta_session_database
    command: bash -c "redis-server --requirepass senha"
    networks:
      - etl-conta_network
    ports:
      - "6379:6379"
    volumes:
      - "redis_db:/data"

  #redis-commander
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: etl-conta_redis-commander
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=senha
    ports:
      - "8083:8081"  
    networks:
      - etl-conta_network


volumes:
  redis_db:
    driver: "local"
  mongo-db:
    driver: "local"
  mongo-configdb:
    driver: "local" 

networks:
  etl-conta_network:
    driver: bridge
